### ISSUE TITLE
Enable SCAN_INTERVAL for entities

### ISSUE THREAD

**Issue by minix1234** [minix1234/hacore_opcua#2]
the current basic sensor does not allow for setting the generic SCAN_INTERVAL settings.  it appears that we should be able to pull it out from the YAML configuration and input it into the entity setup in a similar fashion to the generic sensor [platform](https://github.com/home-assistant/core/blob/dev/homeassistant/components/sensor/__init__.py) .

```
from datetime import timedelta

SCAN_INTERVAL = timedelta(seconds=30)

async def async_setup(hass, config):
    """Track states and offer events for sensors."""
    component = hass.data[DOMAIN] = EntityComponent(
        _LOGGER, DOMAIN, hass, SCAN_INTERVAL
    )
```

**Comment by minix1234** [comment]
additional resources

[](url)

[developer documents](https://developers.home-assistant.io/docs/integration_fetching_data/#separate-polling-for-each-individual-entity)

**Comment by minix1234** [comment]
This is actually taken care of in the base structure of the sensor.py, one just needs to add a `scan_interval: ##` entry into the sensor definition as per below.

```YAML
- platform: opcua
  scan_interval: 10
  nodes:
    - name: Sensor1
      hub: WAGO_OPC_UA
      nodeid: "ns=4;s=|var|WAGO 750-8101 PFC100 2ETH.Application.Publish_NativeMQTT.dwMyCounter"
      unit_of_measurement: degrees
```
