### ISSUE TITLE
OPC-UA

### ISSUE THREAD

**Issue by joeduck** [minix1234/hacore_opcua#8]
Hi,

try this component, but it does not work with the actual HA Version because "setup_Sensors". Can you help?

Thanks, Jochen

**Comment by minix1234** [comment]
howdy,

which HA version.  I have the latest and it's still functional

**Comment by minix1234** [comment]
also can you provide the your config and OPC us target details.

without any of that info there is limit help I can provide

**Comment by minix1234** [comment]
for example here as some 'hub' configuration examples


```yaml
opcua:
  - name: target1
    url: "opc.tcp://192.168.50.113:4840/"
    session_timeout: 600000
    secure_timeout: 600000

  - name: target2
    url: "opc.tcp://192.168.50.113:4840/"
    application_uri: "urn:example.org:FreeOpcUa:python-opcua"
    session_timeout: 600000
    secure_timeout: 600000
    security_string: "Basic256Sha256,SignAndEncrypt,/ssl/certificate-example.der,/ssl/private-key-example.pem"

  - name: prosys
    url: "opc.tcp://192.168.50.113:53530/OPCUA/SimulationServer"
    session_timeout: 600000
    secure_timeout: 600000
    username: "prosys"
    password: "prosys"    
    #application_uri: "urn:example.org:FreeOpcUa:python-opcua"
    #security_string: "Basic256Sha256,SignAndEncrypt,/ssl/certificate-example.der,/ssl/private-key-example.pem"

```

**Comment by minix1234** [comment]
and some tag type configs


```yaml
sensor:

  - platform: opcua
    scan_interval: 3600
    nodes:
      - name: Sensor-1
        hub: target1
        nodeid: "ns=1;i=43840"
        unit_of_measurement: degrees
        

      - name: Sensor-2
        hub: target1
        nodeid: "ns=1;i=51028"
        unit_of_measurement: degrees
```
